In [66]:
import pandas as pd
import numpy as np

In [67]:
# Create a mask to subset data by year
def Mask(year, df):
    mask_year = df[(df.Date == year)]
    return(mask_year)

In [68]:
def DiffPerc(df, sort_year, order):
    # This function inputs a dataframe, and then groupsby count values for each subject and year. 
    # It then converts those subject heading counts into a percentage of all counts for a year by dividing each subject heading by total checkout counts for the year.
    # It then merges all of these new columns into a new dataframe 
    
    # use mask function to subset by year
    subset_2018 = Mask('2018', df)
    subset_2019 = Mask('2019', df)
    subset_2020 = Mask('2020', df)
    subset_2021 = Mask('2021', df)
    subset_2022 = Mask('2022', df)
    subset_2023 = Mask('2023', df)
    
    # group by counts for every year and subject
    counts_2018 = subset_2018.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2019 = subset_2019.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2020 = subset_2020.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2021 = subset_2021.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2022 = subset_2022.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    counts_2023 = subset_2023.groupby(['Subjects', 'Date']).size().reset_index(name='Counts').sort_values(by=['Counts'], ascending=[False])
    
     # create total checkouts variable for every year
    checkouts2018 = counts_2018['Counts'].sum()
    checkouts2019 = counts_2019['Counts'].sum()
    checkouts2020 = counts_2020['Counts'].sum()
    checkouts2021 = counts_2021['Counts'].sum()
    checkouts2022 = counts_2022['Counts'].sum()
    checkouts2023 = counts_2023['Counts'].sum()

    
    # create counts variable for every year

    counts_2018['Subj %'] = counts_2018['Counts'] / checkouts2018

    counts_2019['Subj %'] = counts_2019['Counts'] / checkouts2019
 
    counts_2020['Subj %'] = counts_2020['Counts'] / checkouts2020
 
    counts_2021['Subj %'] = counts_2021['Counts'] / checkouts2021
 
    counts_2022['Subj %'] = counts_2022['Counts'] / checkouts2022
 
    counts_2023['Subj %'] = counts_2023['Counts'] / checkouts2023
    
    # merge columns into a singular dataframe
    merged_df = pd.merge(counts_2018, counts_2019, how='left', on='Subjects')
    merged_df = merged_df.rename(columns={'Date_x' : 'Date 2018',
                    'Counts_x' : 'Counts 2018',
                'Subj %_x' : 'Subj % 2018',
                'Date_y' : 'Date 2019',
                    'Counts_y' : 'Counts 2019',
                'Subj %_y' : 'Subj % 2019'})
    
    merged_df2 = pd.merge(merged_df, counts_2020, how='left', on='Subjects')
    merged_df2 = merged_df2.rename(columns={'Date' : 'Date 2020',
                    'Counts' : 'Counts 2020',
                'Subj %' : 'Subj % 2020'})
    
    merged_df3 = pd.merge(merged_df2, counts_2021, how='left', on='Subjects')
    merged_df3 = merged_df3.rename(columns={'Date' : 'Date 2021',
                    'Counts' : 'Counts 2021',
                'Subj %' : 'Subj % 2021'})
    
    merged_df4 = pd.merge(merged_df3, counts_2022, how='left', on='Subjects')
    merged_df4 = merged_df4.rename(columns={'Date' : 'Date 2022',
                    'Counts' : 'Counts 2022',
                'Subj %' : 'Subj % 2022'})
    
    merged_df5 = pd.merge(merged_df4, counts_2023, how='left', on='Subjects')
    merged_df5 = merged_df5.rename(columns={'Date' : 'Date 2023',
                    'Counts' : 'Counts 2023',
                'Subj %' : 'Subj % 2023'})
    
    # subset df
    merged_df5 =merged_df5[['Subjects', 'Counts 2018', 'Counts 2019', 'Counts 2020', 'Counts 2021', 'Counts 2022', 'Counts 2023',
                            'Subj % 2018', 'Subj % 2019', 'Subj % 2020', 'Subj % 2021', 'Subj % 2022', 'Subj % 2023']]

    # create new column that measures subject heading growth as a decimal by substracting subject % 2023 -  subject # 2018
    merged_df5['2023 Diff 2018'] = merged_df5['Subj % 2023'] - merged_df5['Subj % 2018']
    merged_df5['2023 Diff 2020'] = merged_df5['Subj % 2023'] - merged_df5['Subj % 2020']
    merged_df5['2022 Diff 2018'] = merged_df5['Subj % 2022'] - merged_df5['Subj % 2018']
    merged_df5['2021 Diff 2018'] = merged_df5['Subj % 2021'] - merged_df5['Subj % 2018']
    merged_df5['2020 Diff 2018'] = merged_df5['Subj % 2020'] - merged_df5['Subj % 2018']
    merged_df5['2019 Diff 2018'] = merged_df5['Subj % 2019'] - merged_df5['Subj % 2018']

    # function to enable a sort year and ascending or deescending
    merged_df5 = merged_df5.sort_values(by=[sort_year], ascending=[order]).reset_index(drop=True)

    # reorder the columns
    merged_df5 = merged_df5[['Subjects', 'Counts 2018', 'Counts 2019', 'Counts 2020', 'Counts 2021', 'Counts 2022', 'Counts 2023',
                             'Subj % 2018', 'Subj % 2019', 'Subj % 2020', 'Subj % 2021', 'Subj % 2022', 'Subj % 2023', 
                             '2019 Diff 2018', '2020 Diff 2018','2021 Diff 2018', '2022 Diff 2018',  '2023 Diff 2018', '2023 Diff 2020']]

  
    return merged_df5

In [69]:
def SubjectHeadingoverlaps(df, SubjectHeading1, SubjectHeading2, Date):
    df = df.copy()
    df = df[(df['Subjects'] == SubjectHeading1) | (df['Subjects'] == SubjectHeading2)]
    df = df[df['Date'] == Date]
    non_dupes = df['Item Loan Id'].value_counts() == 1
    non_dupes_sum = non_dupes.sum()
    return print(non_dupes_sum, "check out does not have both subject headings for", Date)

In [70]:
pd.set_option('display.max_columns', None)
three_df = pd.read_csv('ThreeSubjectheadings.csv')
one_df = pd.read_csv('OneSubjectHeading.csv')

In [71]:
# rename columns
one_df = one_df.rename(columns={'Title (Complete)' : 'Title',
                   'Permanent Call Number' : 'Call Number',
               'Loan Date' : 'Date'})

#convert to string and change year to whole year
one_df['Date'] = one_df['Date'].astype(str).str[-4:]
one_df.head(5)

,Item Loan Id,Date,In House Loan Indicator,Barcode,Call Number,Circulation Library Code,Owning Library Code,Title,Author,Subjects,MMS Id,Subjects (Names)
0,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Cities and towns,9913933350001701,NaN
1,2252959196040001701,2018,N,31951000140967E,E159 .H77,TARCH,TARCH,Presence of the past ; a history of the preser...,"Hosmer, Charles Bridgham, 1932-",Monuments--Conservation and restoration--Unite...,9930689970001701,NaN
2,2252965815260001701,2018,N,31951P012191854,Unknown,TARCH,TARCH,Topos : European landscape magazine.,NaN,Landscape architecture--Europe--Periodicals.,9929887730001701,NaN
3,2252965816190001701,2018,N,31951P012191862,Unknown,TARCH,TARCH,Topos : European landscape magazine.,NaN,Landscape architecture--Europe--Periodicals.,9929887730001701,NaN
4,2252965817370001701,2018,N,31951P012055993,Unknown,TARCH,TARCH,Topos : European landscape magazine.,NaN,Landscape architecture--Europe--Periodicals.,9929887730001701,NaN

In [72]:
# rename columns
three_df = three_df.rename(columns={'Title (Complete)' : 'Title',
                   'Permanent Call Number' : 'Call Number',
               'Loan Date' : 'Date'})

#convert to string and change year to whole year
three_df['Date'] = three_df['Date'].astype(str).str[-4:]
three_df.head(5)

,Item Loan Id,Date,In House Loan Indicator,Barcode,Call Number,Circulation Library Code,Owning Library Code,Title,Author,Subjects,MMS Id,Subjects (Names)
0,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Cities and towns,9.913933e+15,NaN
1,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Metropolitan areas,9.913933e+15,NaN
2,2252958767220001701,2018,N,31951D01848189P,HT119 .S65 2000,TARCH,TARCH,Postmetropolis : critical studies of cities an...,"Soja, Edward W.",Urbanization,9.913933e+15,NaN
3,2252959196040001701,2018,N,31951000140967E,E159 .H77,TARCH,TARCH,Presence of the past ; a history of the preser...,"Hosmer, Charles Bridgham, 1932-",Monuments--Conservation and restoration--Unite...,9.930690e+15,NaN
4,2252959196040001701,2018,N,31951000140967E,E159 .H77,TARCH,TARCH,Presence of the past ; a history of the preser...,"Hosmer, Charles Bridgham, 1932-",Historic buildings--United States,9.930690e+15,NaN

In [74]:
RawDataCounts = pd.read_csv('ArchitectureRawData.csv')
RawDataCounts = RawDataCounts.rename(columns={'Title (Complete)' : 'Title',
                   'Permanent Call Number' : 'Call Number',
               'Loan Date' : 'Date'})

#convert to string and change year to whole year
RawDataCounts['Date'] = RawDataCounts['Date'].astype(str).str[-4:]

LoanCounts2018 = Mask('2018', RawDataCounts)
LoanCounts2020 = Mask('2020', RawDataCounts)
LoanCounts2023 = Mask('2023', RawDataCounts)

print('The 2018 loan usage count is:', len(LoanCounts2018), '; The 2020 loan usage count is: ', len(LoanCounts2020), '; The 2023 loan usage count is: ', len(LoanCounts2023))

The 2018 loan usage count is: 5996 ; The 2020 loan usage count is:  2012 ; The 2023 loan usage count is:  2630

In [73]:
# get the number of unique loan records because loans were multiplied due to breaking up subject headings
unique_loans = three_df['Item Loan Id'].nunique()
unique_loans
t = three_df[(three_df['Subjects'] == 'Architecture--Spain--Periodicals.')]
t2023 = t[t['Date'] == '2023']
t2018 = t[t['Date'] == '2018']
len(t2023) - len(t2018) 
unique_loans

20588

unique_loans_2023 = three_df.copy()
unique_loans_2023 = unique_loans_2023[unique_loans_2023['Date'] == '2023']
unique_loans_2023 = unique_loans_2023.nunique()
unique_loans_2023

def YearLoanNumber(df, Date):
    df = df.copy()
    df = df[df['Date'] == Date]
    distinct_loan_number = df['Item Loan Id'].nunique()
    return distinct_loan_number

YearLoanNumber(three_df, '2023')

In [75]:
# Utilized DiffPerc function to create dataframe that generates growth statistics for each subject heading 
# This dataset is from the version that utilizes the first three subject headings
# Sorted  by 2023 Diff 2018 on all there subjects (largest to smallest positive change)
# Percentages are not actually a percentage. It is a decimal.
diff_three_df2023 = DiffPerc(three_df, '2023 Diff 2018', False)
diff_three_df2023.head()

,Subjects,Counts 2018,Counts 2019,Counts 2020,Counts 2021,Counts 2022,Counts 2023,Subj % 2018,Subj % 2019,Subj % 2020,Subj % 2021,Subj % 2022,Subj % 2023,2019 Diff 2018,2020 Diff 2018,2021 Diff 2018,2022 Diff 2018,2023 Diff 2018,2023 Diff 2020
0,Architecture--Espagne--20e siècle--Périodiques.,108,158.0,24.0,50.0,129.0,97.0,0.007502,0.011714,0.004845,0.009615,0.019767,0.015130,0.004213,-0.002657,2.113822e-03,0.012266,0.007629,0.010286
1,Architecture--Spain--Periodicals.,109,159.0,25.0,50.0,129.0,97.0,0.007571,0.011788,0.005046,0.009615,0.019767,0.015130,0.004217,-0.002525,2.044363e-03,0.012196,0.007559,0.010084
2,"Architecture, Domestic--Designs and plans",27,51.0,14.0,23.0,20.0,33.0,0.001875,0.003781,0.002826,0.004423,0.003065,0.005147,0.001906,0.000951,2.547686e-03,0.001189,0.003272,0.002321
3,Architecture domestique.,3,16.0,1.0,7.0,3.0,21.0,0.000208,0.001186,0.000202,0.001346,0.000460,0.003276,0.000978,-0.000007,1.137777e-03,0.000251,0.003067,0.003074
4,"Architecture, Modern--20th century--Designs an...",36,45.0,7.0,13.0,13.0,35.0,0.002501,0.003336,0.001413,0.002500,0.001992,0.005459,0.000836,-0.001088,-5.209419e-07,-0.000508,0.002959,0.004046

In [76]:
# Utilized DiffPerc function to create dataframe that generates growth statistics for each subject heading 
# This dataset is from the version that utilizes only the first subject heading
# Sorted  by 2023 Diff 2018 on all there subjects (largest to smallest positive change)
# We didn't end up using this one.
diff_one_df2023 = DiffPerc(one_df, '2023 Diff 2018', False)
diff_one_df2023.head()

,Subjects,Counts 2018,Counts 2019,Counts 2020,Counts 2021,Counts 2022,Counts 2023,Subj % 2018,Subj % 2019,Subj % 2020,Subj % 2021,Subj % 2022,Subj % 2023,2019 Diff 2018,2020 Diff 2018,2021 Diff 2018,2022 Diff 2018,2023 Diff 2018,2023 Diff 2020
0,Architecture--Spain--Periodicals.,109,159.0,25.0,50.0,129.0,97.0,0.018528,0.029105,0.012594,0.024073,0.049558,0.037641,0.010577,-0.005934,0.005545,0.031030,0.019113,0.025046
1,"Architecture, Domestic--Designs and plans",14,29.0,6.0,14.0,11.0,27.0,0.002380,0.005308,0.003023,0.006740,0.004226,0.010477,0.002929,0.000643,0.004361,0.001846,0.008098,0.007455
2,Architecture--Environmental aspects,23,30.0,26.0,6.0,9.0,25.0,0.003910,0.005491,0.013098,0.002889,0.003458,0.009701,0.001582,0.009189,-0.001021,-0.000452,0.005792,-0.003397
3,Landscape architecture,22,32.0,8.0,15.0,17.0,20.0,0.003740,0.005858,0.004030,0.007222,0.006531,0.007761,0.002118,0.000291,0.003482,0.002791,0.004021,0.003731
4,"Building, Wooden",16,23.0,2.0,5.0,16.0,16.0,0.002720,0.004210,0.001008,0.002407,0.006147,0.006209,0.001490,-0.001712,-0.000312,0.003427,0.003489,0.005201

In [77]:
# Compare Three subject heading vs one subject heading data
three2020 = diff_three_df2023 
three2020 = three2020[['Subjects', 'Subj % 2020']]

# rename columns and sort values
three2020 = three2020.rename(columns={'Subj % 2020': 'Three Subjects % 2020'})
three2020 = three2020.sort_values('Three Subjects % 2020', ascending=False).reset_index(drop=True)

one2020 = diff_one_df2023
one2020 = one2020[['Subjects', 'Subj % 2020']]

# rename columns and sort values 
one2020 = one2020.rename(columns={'Subjects': 'One Subjects', 'Subj % 2020': 'One Subjects % 2020'})
one2020 = one2020.sort_values('One Subjects % 2020', ascending=False).reset_index(drop=True)

#comp_df = pd.merge(three2023, one2023, how='left', on='Subjects')
comp_df2020 = pd.concat([three2020, one2020], axis=1)
comp_df2020 = comp_df2020.head(15)
comp_df2020

,Subjects,Three Subjects % 2020,One Subjects,One Subjects % 2020
0,"Architecture, Modern--20th century",0.016149,"Architecture, Modern--20th century",0.015617
1,City planning,0.011506,City planning,0.015617
2,Architecture--Environmental aspects,0.008074,Architecture--Environmental aspects,0.013098
3,Architecture--Periodicals,0.007872,Architecture--Spain--Periodicals.,0.012594
4,"Architecture, Modern--21st century",0.007065,"Architecture, Domestic--Japan",0.009068
5,Architectural design,0.006056,Architecture and society,0.008060
6,Architecture and society,0.006056,Architectural design,0.007053
7,Architecture--Human factors,0.006056,Architecture--Philosophy,0.006549
8,Sustainable architecture,0.005854,Architecture--Japan--History--20th century,0.005542
9,Architecture,0.005450,Architecture--Periodicals,0.005038
10,Architecture--Spain--Periodicals.,0.005046,Architecture--Human factors,0.005038
11,Architecture--Philosophy,0.004845,"Alexander--VII,--Pope,--1599-1667",0.004534
12,Architecture--Espagne--20e siècle--Périodiques.,0.004845,City planning--Environmental aspects,0.004534
13,Landscape architecture,0.004239,Landscape architecture,0.004030
14,Architecture--Japan--History--20th century,0.004239,City planning--United States,0.004030

In [78]:
# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHChange2018 = diff_three_df2023.copy()
ThreeSHChange2018 = ThreeSHChange2018.rename(columns={"Counts 2018": "2018 Loan Number", "Counts 2023": "2023 Loan Number", "Subj % 2018": "2018 Subj Collection %", "Subj % 2023": "2023 Subj Collection %"})
# '2018 Subj Collection %'
# normalize decimals to percentage
ThreeSHChange2018['2018 Subj Collection %'] = ThreeSHChange2018['2018 Subj Collection %'] 
ThreeSHChange2018['2023 Subj Collection %'] = ThreeSHChange2018['2023 Subj Collection %'] 

# subtract years to see change
ThreeSHChange2018['2023 - 2018 Subj Collection % Change'] = ThreeSHChange2018['2023 Subj Collection %'] - ThreeSHChange2018['2018 Subj Collection %']
ThreeSHChange2018['Loan Number Change'] = ThreeSHChange2018['2023 Loan Number'] - ThreeSHChange2018['2018 Loan Number'] 


#multiplier
ThreeSHChange2018['Subj Multi Growth Factor'] = ThreeSHChange2018['2023 Subj Collection %'] / ThreeSHChange2018['2018 Subj Collection %']
ThreeSHChange2018 = ThreeSHChange2018[['Subjects', '2018 Loan Number', '2023 Loan Number', 'Loan Number Change', '2018 Subj Collection %', 
                                       '2023 Subj Collection %', '2023 - 2018 Subj Collection % Change', 'Subj Multi Growth Factor']]


# sort table by 2023 diff 2020 collection %
ThreeSHChange2018 = ThreeSHChange2018.sort_values('2023 - 2018 Subj Collection % Change', ascending=False)

# reindex to start at 1
ThreeSHChange2018 = ThreeSHChange2018.head(10)
ThreeSHChange2018.index = ThreeSHChange2018.index + 1

# create a table title
#ThreeSHChange2018 = ThreeSHChange2018.style.set_caption('Table 1: Top 10 Subject Headings Growth From 2018 to 2023')
ThreeSHChange2018

,Subjects,2018 Loan Number,2023 Loan Number,Loan Number Change,2018 Subj Collection %,2023 Subj Collection %,2023 - 2018 Subj Collection % Change,Subj Multi Growth Factor
1,Architecture--Espagne--20e siècle--Périodiques.,108,97.0,-11.0,0.007502,0.015130,0.007629,2.016946
2,Architecture--Spain--Periodicals.,109,97.0,-12.0,0.007571,0.015130,0.007559,1.998442
3,"Architecture, Domestic--Designs and plans",27,33.0,6.0,0.001875,0.005147,0.003272,2.744710
4,Architecture domestique.,3,21.0,18.0,0.000208,0.003276,0.003067,15.719701
5,"Architecture, Modern--20th century--Designs an...",36,35.0,-1.0,0.002501,0.005459,0.002959,2.183292
6,Architecture--Environmental aspects,60,43.0,-17.0,0.004168,0.006707,0.002540,1.609398
7,Architecture--Japan--History--20th century,41,33.0,-8.0,0.002848,0.005147,0.002300,1.807492
8,Architecture--Human factors,51,37.0,-14.0,0.003542,0.005771,0.002229,1.629213
9,Sustainable architecture,54,36.0,-18.0,0.003751,0.005615,0.001865,1.497114
10,Architecture,127,68.0,-59.0,0.008821,0.010607,0.001785,1.202407

In [79]:
SubjectHeadingoverlaps(three_df,'Architecture--Spain--Periodicals.', 'Architecture--Espagne--20e siècle--Périodiques.', '2018'), SubjectHeadingoverlaps(three_df,'Architecture--Spain--Periodicals.', 'Architecture--Espagne--20e siècle--Périodiques.', '2023')

1 check out does not have both subject headings for 2018
0 check out does not have both subject headings for 2023

(None, None)

In [80]:
# plotting sorted  by 2020 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.copy()
ThreeSHGrowth2023 = ThreeSHGrowth2023.rename(columns={"Counts 2018": "2018 Loan Number", 
                                                      "Counts 2020": "2020 Loan Number", 
                                                      "Counts 2023": "2023 Loan Number",
                                                      "Subj % 2018": "2018 Subj Collection %", 
                                                      "Subj % 2020": "2020 Subj Collection %", 
                                                      "Subj % 2023": "2023 Subj Collection %"})

# subtract years to see change
ThreeSHGrowth2023['2020 - 2018 Subj Collection % Change'] = ThreeSHGrowth2023['2020 Subj Collection %'] - ThreeSHGrowth2023['2018 Subj Collection %']
ThreeSHGrowth2023['Loan Number Change'] = ThreeSHGrowth2023['2020 Loan Number'] - ThreeSHGrowth2023['2018 Loan Number'] 

#multiplier
ThreeSHGrowth2023['Subj Multi Growth Factor'] = ThreeSHGrowth2023['2020 Subj Collection %'] / ThreeSHGrowth2023['2018 Subj Collection %']


ThreeSHGrowth2023 = ThreeSHGrowth2023[['Subjects', '2018 Loan Number', '2020 Loan Number', '2023 Loan Number', 'Loan Number Change', '2018 Subj Collection %',
                                       '2020 Subj Collection %', '2023 Subj Collection %', '2020 - 2018 Subj Collection % Change', 'Subj Multi Growth Factor']]

# sort table by 2023 diff 2020 collection %
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('2020 - 2018 Subj Collection % Change', ascending=False)


# reindex to start at 1
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(10).reset_index(drop=True)
ThreeSHGrowth2023.index = ThreeSHGrowth2023.index + 1

# create a table title
#ThreeSHChange2018 = ThreeSHChange2018.style.set_caption('Table 1: Top 10 Subject Headings Growth From 2018 to 2023')
ThreeSHGrowth2023

,Subjects,2018 Loan Number,2020 Loan Number,2023 Loan Number,Loan Number Change,2018 Subj Collection %,2020 Subj Collection %,2023 Subj Collection %,2020 - 2018 Subj Collection % Change,Subj Multi Growth Factor
1,Architecture--Environmental aspects,60,40.0,43.0,-20.0,0.004168,0.008074,0.006707,0.003907,1.937424
2,City planning,117,57.0,33.0,-60.0,0.008127,0.011506,0.005147,0.003379,1.415810
3,"Architecture, Domestic--Japan",15,18.0,6.0,3.0,0.001042,0.003633,0.000936,0.002592,3.487364
4,Architecture--Human factors,51,30.0,37.0,-21.0,0.003542,0.006056,0.005771,0.002513,1.709492
5,Sustainable architecture,54,29.0,36.0,-25.0,0.003751,0.005854,0.005615,0.002103,1.560703
6,"Architecture, Baroque--Italy--Rome",4,11.0,7.0,7.0,0.000278,0.002220,0.001092,0.001943,7.991875
7,Architecture--Japan--History--21st century.,10,12.0,8.0,2.0,0.000695,0.002422,0.001248,0.001728,3.487364
8,"Alexander--VII,--Pope,--1599-1667",2,9.0,6.0,7.0,0.000139,0.001817,0.000936,0.001678,13.077614
9,Architecture and society--United States,12,12.0,6.0,0.0,0.000834,0.002422,0.000936,0.001589,2.906136
10,ARCHITECTURE / General.,18,14.0,10.0,-4.0,0.001250,0.002826,0.001560,0.001576,2.260328

# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHChange2018 = diff_three_df2023.rename(columns={"2023 Diff 2018": "2023 Growth %"})
ThreeSHChange2018 = ThreeSHChange2018.sort_values('2023 Growth %', ascending=False)

# normalize decimals to percentage
ThreeSHChange2018['Subj % 2018'] = ThreeSHChange2018['Subj % 2018'] * 100
ThreeSHChange2018['Subj % 2023'] = ThreeSHChange2018['Subj % 2023'] * 100

# limit to top 20 growing subject headings and select 2018 and 2023 years only
colors = colors=['darkgray','gray']
ThreeSHChange2018 = ThreeSHChange2018.head(20).sort_values('2023 Growth %', ascending=True).plot(x="Subjects", y=['Subj % 2018', 'Subj % 2023'], kind="barh", color=colors) 
ThreeSHChange2018.set_title('Figure 1: Top 20 Subject Headings Growth From 2018 to 2023')

ThreeSHChange2018

In [81]:
# plotting sorted  by 2023 Diff 2020 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.copy()
ThreeSHGrowth2023 = ThreeSHGrowth2023.rename(columns={"Counts 2018": "2018 Loan Number", 
                                                      "Counts 2020": "2020 Loan Number", 
                                                      "Counts 2023": "2023 Loan Number",
                                                      "Subj % 2018": "2018 Subj Collection %", 
                                                      "Subj % 2020": "2020 Subj Collection %", 
                                                      "Subj % 2023": "2023 Subj Collection %"})

# subtract years to see change
ThreeSHGrowth2023['2023 - 2020 Subj Collection % Change'] = ThreeSHGrowth2023['2023 Subj Collection %'] - ThreeSHGrowth2023['2020 Subj Collection %']
ThreeSHGrowth2023['Loan Number Change'] = ThreeSHGrowth2023['2023 Loan Number'] - ThreeSHGrowth2023['2020 Loan Number'] 

#multiplier
ThreeSHGrowth2023['Subj Multi Growth Factor'] = ThreeSHGrowth2023['2023 Subj Collection %'] / ThreeSHGrowth2023['2020 Subj Collection %']


ThreeSHGrowth2023 = ThreeSHGrowth2023[['Subjects', '2018 Loan Number', '2020 Loan Number', '2023 Loan Number', 'Loan Number Change', '2018 Subj Collection %',
                                       '2020 Subj Collection %', '2023 Subj Collection %', '2023 - 2020 Subj Collection % Change', 'Subj Multi Growth Factor']]

# sort table by 2023 diff 2020 collection %
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('2023 - 2020 Subj Collection % Change', ascending=False)


# reindex to start at 1
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(10).reset_index(drop=True)
ThreeSHGrowth2023.index = ThreeSHGrowth2023.index + 1

# create a table title
#ThreeSHChange2018 = ThreeSHChange2018.style.set_caption('Table 1: Top 10 Subject Headings Growth From 2018 to 2023')
ThreeSHGrowth2023

,Subjects,2018 Loan Number,2020 Loan Number,2023 Loan Number,Loan Number Change,2018 Subj Collection %,2020 Subj Collection %,2023 Subj Collection %,2023 - 2020 Subj Collection % Change,Subj Multi Growth Factor
1,Architecture--Periodicals,278,39.0,130.0,91.0,0.019310,0.007872,0.020278,0.012405,2.575781
2,Architecture--Espagne--20e siècle--Périodiques.,108,24.0,97.0,73.0,0.007502,0.004845,0.015130,0.010286,3.123135
3,Architecture--Spain--Periodicals.,109,25.0,97.0,72.0,0.007571,0.005046,0.015130,0.010084,2.998209
4,Architecture,127,27.0,68.0,41.0,0.008821,0.005450,0.010607,0.005157,1.946146
5,"Architecture, Modern--20th century--Designs an...",36,7.0,35.0,28.0,0.002501,0.001413,0.005459,0.004046,3.863672
6,Architecture domestique.,3,1.0,21.0,20.0,0.000208,0.000202,0.003276,0.003074,16.227422
7,"Architecture, Domestic--Designs and plans",27,14.0,33.0,19.0,0.001875,0.002826,0.005147,0.002321,1.821445
8,"Andō, Tadao,--1941-",40,4.0,19.0,15.0,0.002778,0.000807,0.002964,0.002156,3.670488
9,Landscape architecture,62,21.0,38.0,17.0,0.004306,0.004239,0.005927,0.001688,1.398281
10,Building--Periodicals,54,5.0,17.0,12.0,0.003751,0.001009,0.002652,0.001642,2.627297

# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Growth %"})
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('2023 Growth %', ascending=False)

# normalize decimals to percentage
ThreeSHGrowth2023['Subj % 2018'] = ThreeSHGrowth2023['Subj % 2018'] * 100
ThreeSHGrowth2023['Subj % 2020'] = ThreeSHGrowth2023['Subj % 2020'] * 100
ThreeSHGrowth2023['Subj % 2023'] = ThreeSHGrowth2023['Subj % 2023'] * 100

# subtract years to see change
ThreeSHGrowth2023['Subj% Change'] = ThreeSHGrowth2023['Subj % 2023'] - ThreeSHGrowth2023['Subj % 2020']

#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)
ThreeSHGrowth2023 = ThreeSHGrowth2023[['Subjects', 'Subj % 2018', 'Subj % 2020', 'Subj % 2023', 'Subj% Change']]

# reindex to start at 1
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(10).reset_index(drop=True)
ThreeSHGrowth2023.index = ThreeSHGrowth2023.index + 1

# create a table title
ThreeSHGrowth2023 = ThreeSHGrowth2023.style.set_caption('Table 2: Top 10 Subject Headings Growth From 2020 to 2023')
ThreeSHGrowth2023

# plotting sorted by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHGrowth2023 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Growth %"})
ThreeSHGrowth2023 = ThreeSHGrowth2023.sort_values('2023 Growth %', ascending=False)

# normalize decimals to percentage
ThreeSHGrowth2023['Subj % 2018'] = ThreeSHGrowth2023['Subj % 2018'] * 100
ThreeSHGrowth2023['Subj % 2020'] = ThreeSHGrowth2023['Subj % 2020'] * 100
ThreeSHGrowth2023['Subj % 2023'] = ThreeSHGrowth2023['Subj % 2023'] * 100

# limit to top 20 growing subject headings and select 2018, 2020, and 2023 years
colors = colors=['darkgray', 'gray','dimgray']
ThreeSHGrowth2023 = ThreeSHGrowth2023.head(20).sort_values('2023 Growth %', ascending=True).plot(x="Subjects", y=['Subj % 2018', 'Subj % 2020', 'Subj % 2023'], kind="barh", color=colors) 
ThreeSHGrowth2023.set_title('Figure 2: Top 20 Subject Headings Growth From 2020 to 2023')

ThreeSHGrowth2023

In [82]:
# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest negative change)
ThreeSHDec2023 = diff_three_df2023.copy()
ThreeSHDec2023 = ThreeSHDec2023.rename(columns={"Counts 2018": "2018 Loan Number", 
                                                "Counts 2020": "2020 Loan Number", 
                                                "Counts 2023": "2023 Loan Number",
                                                "Subj % 2018": "2018 Subj Collection %", 
                                                "Subj % 2020": "2020 Subj Collection %", 
                                                "Subj % 2023": "2023 Subj Collection %"})
# subtract years to see change
ThreeSHDec2023['2023 - 2018 Subj Collection % Change'] = ThreeSHDec2023['2023 Subj Collection %'] - ThreeSHDec2023['2018 Subj Collection %']

ThreeSHDec2023['Loan Number Change'] = ThreeSHDec2023['2023 Loan Number'] - ThreeSHDec2023['2018 Loan Number'] 


#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)

#multiplier
ThreeSHDec2023['Subj Multi Growth Factor'] = ThreeSHDec2023['2023 Subj Collection %'] / ThreeSHDec2023['2018 Subj Collection %']
ThreeSHDec2023 = ThreeSHDec2023[['Subjects', '2018 Loan Number','2020 Loan Number', '2023 Loan Number','Loan Number Change', 
                                 '2018 Subj Collection %','2020 Subj Collection %', '2023 Subj Collection %', '2023 - 2018 Subj Collection % Change', 
                                 'Subj Multi Growth Factor']]


# sort table by growth
ThreeSHDec2023 = ThreeSHDec2023.sort_values('2023 - 2018 Subj Collection % Change', ascending=True)

# sort table by subj num growth change
#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj Multi Growth Factor', ascending=False).reset_index(drop=True)

# reindex to start at 1
ThreeSHDec2023 = ThreeSHDec2023.head(10).reset_index(drop=True)
ThreeSHDec2023.index = ThreeSHDec2023.index + 1

# create a table title
#ThreeSHDec2020 = ThreeSHDec2020.style.set_caption('Table 3: Top 10 Decreasing Subject Headings From 2020 to 2023')
ThreeSHDec2023

,Subjects,2018 Loan Number,2020 Loan Number,2023 Loan Number,Loan Number Change,2018 Subj Collection %,2020 Subj Collection %,2023 Subj Collection %,2023 - 2018 Subj Collection % Change,Subj Multi Growth Factor
1,City planning,117,57.0,33.0,-84.0,0.008127,0.011506,0.005147,-0.002979,0.633395
2,Periodicals,44,4.0,4.0,-40.0,0.003056,0.000807,0.000624,-0.002432,0.204152
3,"Architecture, Modern--20th century",225,80.0,89.0,-136.0,0.015628,0.016149,0.013882,-0.001746,0.888288
4,Architecture--Philosophy,99,24.0,33.0,-66.0,0.006876,0.004845,0.005147,-0.001729,0.748557
5,"Architecture, Modern--20th century--Exhibitions",29,5.0,2.0,-27.0,0.002014,0.001009,0.000312,-0.001702,0.154874
6,Architecture--United States--History--20th cen...,67,12.0,20.0,-47.0,0.004654,0.002422,0.003120,-0.001534,0.670350
7,"Architecture, Modern--20th century--Periodicals",22,NaN,1.0,-21.0,0.001528,NaN,0.000156,-0.001372,0.102076
8,"Breuer, Marcel,--1902-1981",23,4.0,2.0,-21.0,0.001598,0.000807,0.000312,-0.001286,0.195276
9,Building--Periodicals,54,5.0,17.0,-37.0,0.003751,0.001009,0.002652,-0.001099,0.706971
10,City planning--Periodicals,29,8.0,6.0,-23.0,0.002014,0.001615,0.000936,-0.001078,0.464622

In [83]:
# plotting sorted  by 2023 Diff 2020 on all three subjects (largest to smallest negative change)
ThreeSHDec2020 = diff_three_df2023.copy()
ThreeSHDec2020 = ThreeSHDec2020.rename(columns={"Counts 2018": "2018 Loan Number", 
                                                      "Counts 2020": "2020 Loan Number", 
                                                      "Counts 2023": "2023 Loan Number",
                                                      "Subj % 2018": "2018 Subj Collection %", 
                                                      "Subj % 2020": "2020 Subj Collection %", 
                                                      "Subj % 2023": "2023 Subj Collection %"})

# subtract years to see change
ThreeSHDec2020['2023 - 2020 Subj Collection % Change'] = ThreeSHDec2020['2023 Subj Collection %'] - ThreeSHDec2020['2020 Subj Collection %']
ThreeSHDec2020['Loan Number Change'] = ThreeSHDec2020['2023 Loan Number'] - ThreeSHDec2020['2020 Loan Number'] 


#multiplier
ThreeSHDec2020['Subj Multi Growth Factor'] = ThreeSHDec2020['2023 Subj Collection %'] / ThreeSHDec2020['2020 Subj Collection %']
ThreeSHDec2020 = ThreeSHDec2020[['Subjects', '2018 Loan Number','2020 Loan Number','2023 Loan Number','Loan Number Change', 
                                 '2018 Subj Collection %','2020 Subj Collection %', '2023 Subj Collection %', 
                                 '2023 - 2020 Subj Collection % Change', 'Subj Multi Growth Factor']]


# sort table by growth
ThreeSHDec2020 = ThreeSHDec2020.sort_values('2023 - 2020 Subj Collection % Change', ascending=True)


# reindex to start at 1
ThreeSHDec2020 = ThreeSHDec2020.head(10).reset_index(drop=True)
ThreeSHDec2020.index = ThreeSHDec2020.index + 1

# create a table title
#ThreeSHDec2020 = ThreeSHDec2020.style.set_caption('Table 4: Top 10 Decreasing Subject Headings From 2020 to 2023')
ThreeSHDec2020

,Subjects,2018 Loan Number,2020 Loan Number,2023 Loan Number,Loan Number Change,2018 Subj Collection %,2020 Subj Collection %,2023 Subj Collection %,2023 - 2020 Subj Collection % Change,Subj Multi Growth Factor
1,City planning,117,57.0,33.0,-24.0,0.008127,0.011506,0.005147,-0.006358,0.447373
2,"Architecture, Domestic--Japan",15,18.0,6.0,-12.0,0.001042,0.003633,0.000936,-0.002698,0.257578
3,"Architecture, Modern--20th century",225,80.0,89.0,9.0,0.015628,0.016149,0.013882,-0.002266,0.859667
4,City planning--Environmental aspects,33,17.0,12.0,-5.0,0.002292,0.003432,0.001872,-0.001560,0.545460
5,Architecture and society--United States,12,12.0,6.0,-6.0,0.000834,0.002422,0.000936,-0.001486,0.386367
6,Architecture--Environmental aspects,60,40.0,43.0,3.0,0.004168,0.008074,0.006707,-0.001367,0.830689
7,Urban renewal,11,8.0,2.0,-6.0,0.000764,0.001615,0.000312,-0.001303,0.193184
8,Buildings--Environmental engineering,9,8.0,2.0,-6.0,0.000625,0.001615,0.000312,-0.001303,0.193184
9,"Sociology, Urban",8,8.0,2.0,-6.0,0.000556,0.001615,0.000312,-0.001303,0.193184
10,ARCHITECTURE / General.,18,14.0,10.0,-4.0,0.001250,0.002826,0.001560,-0.001266,0.551953

# plotting sorted  by 2023 Diff 2018 on all three subjects (largest to smallest positive change)
ThreeSHDec2020 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Decline %"})
ThreeSHDec2020 = ThreeSHDec2020.sort_values('2023 Decline %', ascending=True)

# normalize decimals to percentage
ThreeSHDec2020['Subj % 2018'] = ThreeSHDec2020['Subj % 2018'] * 100
ThreeSHDec2020['Subj % 2020'] = ThreeSHDec2020['Subj % 2020'] * 100
ThreeSHDec2020['Subj % 2023'] = ThreeSHDec2020['Subj % 2023'] *100

# subtract years to see change
ThreeSHDec2020['Subj% Change'] = ThreeSHDec2020['Subj % 2023'] - ThreeSHDec2020['Subj % 2020']

#ThreeSHChange2018 = ThreeSHChange2018.sort_values('Subj% Change', ascending=False)
ThreeSHDec2020 = ThreeSHDec2020[['Subjects', 'Subj % 2018', 'Subj % 2020', 'Subj % 2023', 'Subj% Change']]

# reindex to start at 1
ThreeSHDec2020 = ThreeSHDec2020.head(10).reset_index(drop=True)
ThreeSHDec2020.index = ThreeSHDec2020.index + 1

# create a table title
ThreeSHDec2020 = ThreeSHDec2020.style.set_caption('Table 3: Top 10 Decreasing Subject Headings From 2020 to 2023')
ThreeSHDec2020

# plotting sorted  by 2023 Diff 2018 on all there subjects (largest to smallest negative change)
ThreeSHDec2020 = diff_three_df2023.rename(columns={"2023 Diff 2020": "2023 Decline %"})
ThreeSHDec2020 = ThreeSHDec2020.sort_values('2023 Decline %', ascending=True)

# normalize decimals to percentage
ThreeSHDec2020['Subj % 2018'] = ThreeSHDec2020['Subj % 2018'] * 100
ThreeSHDec2020['Subj % 2020'] = ThreeSHDec2020['Subj % 2020'] * 100
ThreeSHDec2020['Subj % 2023'] = ThreeSHDec2020['Subj % 2023'] * 100

# limit to top 20 decreasing subject headings and select 2018, 2020, and 2023 years
colors = colors=['darkgray', 'gray', 'dimgray']
ThreeSHDec2020 = ThreeSHDec2020.head(20).sort_values('2023 Decline %', ascending=False).plot(x="Subjects", y=['Subj % 2018', 'Subj % 2020', 'Subj % 2023'], kind="barh", color=colors) 
ThreeSHDec2020.set_title('Figure 3: Top 20 Decreasing Subject Headings From 2020 to 2023')

ThreeSHDec2020

In [84]:
# Look up how much the subject headingg Architects--Japan--Interviews. grew from 2018 to 2020
print('The number of Japanese interviews in 2018:', len(three_df[(three_df['Subjects'] == 'Architects--Japan--Interviews.') & (three_df["Date"] == '2018')])), print('The number of Japanese interviews in 2020:',  len(three_df[(three_df['Subjects'] == 'Architects--Japan--Interviews.') & (three_df["Date"] == '2020')]))

The number of Japanese interviews in 2018: 1
The number of Japanese interviews in 2020: 6

(None, None)

In [85]:
# look up Buildings--Remodeling for other use to see how much it grew from 2020 to 2023 
diff_three_df2023[(diff_three_df2023['Subjects'] == 'Buildings--Remodeling for other use')]

,Subjects,Counts 2018,Counts 2019,Counts 2020,Counts 2021,Counts 2022,Counts 2023,Subj % 2018,Subj % 2019,Subj % 2020,Subj % 2021,Subj % 2022,Subj % 2023,2019 Diff 2018,2020 Diff 2018,2021 Diff 2018,2022 Diff 2018,2023 Diff 2018,2023 Diff 2020
19,Buildings--Remodeling for other use,9,5.0,2.0,2.0,14.0,11.0,0.000625,0.000371,0.000404,0.000385,0.002145,0.001716,-0.000254,-0.000221,-0.000241,0.00152,0.001091,0.001312